# ########################################################################## #
#                                                                            #
#                                                        :::      ::::::::   #
#   test.yml                                           :+:      :+:    :+:   #
#                                                    +:+ +:+         +:+     #
#   By: GlaceCoding <github.com/GlaceCoding>       +#+  +:+       +#+        #
#                                                +#+#+#+#+#+   +#+           #
#   Created: 2021/10/11 14:10:04 by GlaceCoding       #+#    #+#             #
#   Updated: 2021/10/11 14:10:51 by GlaceCoding      ###   ########.fr       #
#                                                                            #
# ########################################################################## #

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: install norminette
      run: python3 -m pip install norminette
    - name: test
      run: sh test/test.sh
